RSDK-2022 Add the cartographer module brew package
viamrobotics/homebrew-brews pull request #21
Opened 2023-04-10 17:53 UTC by kkufieta

Ticket: https://viam.atlassian.net/browse/RSDK-2022

* Add the cartographer-module brew package

2023-04-10 19:43 UTC, kkufieta commented on Formula/cartographer-module.rb
> +    bin.install "bin/cartographer-module"
This is the only difference compared to carto-grpc-server.rb

2023-04-10 19:49 UTC, EshaMaharishi commented on Formula/cartographer-module.rb
> +  depends_on "cairo"
Just checking if CartographerModule needs all of these dependencies, like cairo?

2023-04-10 19:49 UTC, EshaMaharishi commented on Formula/cartographer-module.rb
> +    bin.install "viam-cartographer/build/carto_grpc_server"
Checking if we still want this line here, if it's also in carto-grpc-server.rb?

2023-04-10 19:49 UTC, EshaMaharishi commented on Formula/cartographer-module.rb
> +    share.install "viam-cartographer/cartographer/configuration_files/trajectory_builder_3d.lua" => "cartographer/lua_files/"
Do we need all of these for CartographerModule?

2023-04-10 19:49 UTC, EshaMaharishi commented on Formula/cartographer-module.rb
> +class CartographerModule < Formula
Do we need to add something like [this](https://github.com/viamrobotics/homebrew-brews/blob/6511351b8f110686ed5411b828038fc7e19a80c4/.github/workflows/bump-versions.yml#L38-L39) for the new brew target?

2023-04-10 19:51 UTC, kkufieta commented on Formula/cartographer-module.rb
> +class CartographerModule < Formula
ah yes, good catch! Thank you!

2023-04-10 19:54 UTC, kkufieta commented on Formula/cartographer-module.rb
> +  depends_on "cairo"
Yes, the dependencies stay the same. It requires cairo to paint the map that we use to create the pointcloud version of it.

2023-04-10 19:55 UTC, kkufieta commented on Formula/cartographer-module.rb
> +    bin.install "viam-cartographer/build/carto_grpc_server"
Yes, we want to install both necessary binaries needed to run the module, such that the user has to only install this brew package to have a fully functional cartographer module (as opposed to having to install two brew packages separately).

2023-04-10 19:56 UTC, kkufieta commented on Formula/cartographer-module.rb
> +    share.install "viam-cartographer/cartographer/configuration_files/trajectory_builder_3d.lua" => "cartographer/lua_files/"
Yes, the cartographer module brew package installs also the carto-grpc-server, which needs all of the above.

2023-04-10 19:56 UTC, EshaMaharishi commented on Formula/cartographer-module.rb
> +    bin.install "viam-cartographer/build/carto_grpc_server"
Got it, thanks!

2023-04-10 19:56 UTC, EshaMaharishi commented on Formula/cartographer-module.rb
> +    share.install "viam-cartographer/cartographer/configuration_files/trajectory_builder_3d.lua" => "cartographer/lua_files/"
Got it, thanks!

2023-04-10 19:57 UTC, kkufieta commented on Formula/cartographer-module.rb
> +  desc "Viam cartographer modular service"
This is one of two differences compared to carto-grpc-server.rb (the other one being the added binary below).

2023-04-10 20:42 UTC, Otterverse requested changes
So a couple of inline comments as well, but overall... this looks to provide "bin/carto_grpc_server" just like the previous formula does. As such, is there a reason this isn't just replacing the old one? If there is, then it needs a conflicts_with warning at least.

2023-04-10 20:42 UTC, Otterverse commented on Formula/cartographer-module.rb
> +    bin.install "viam-cartographer/build/carto_grpc_server"
Isn't this going to conflict with the carto-grpc-server formula? E.g. they both try to install this same file, right? You probably need to add a conflicts_with against the other formula since they can't both be installed at the same time. Or... just replace the old one with this new one.

2023-04-10 20:42 UTC, Otterverse commented on Formula/cartographer-module.rb
> +    lib.install "viam-cartographer/build/libviam-cartographer.a"
These are static libraries, and theoretically should only ever be needed when compiling, but it doesn't appear this package is including any header files to match these. Are you certain these are needed at runtime?

2023-04-10 20:42 UTC, Otterverse commented on Formula/cartographer-module.rb
> +  depends_on "cairo"
On the same subject, how many of these are only needed during the build, and not during runtime? Ex: I think sphinx-doc isn't needed during runtime. Likewise, googletest is (I think) only for unit tests.

2023-04-11 14:51 UTC, nicksanford commented
> So a couple of inline comments as well, but overall... this looks to provide "bin/carto_grpc_server" just like the previous formula does. As such, is there a reason this isn't just replacing the old one? If there is, then it needs a conflicts_with warning at least.

The slam team would like to be able to get this new formula out & working before needing to update docs. We are trying to prevent the need for lockstep deployments in coordination with Docs updates.

If we can assume nobody is going to use this new formula outside of viam until we update the docs, is the conflict with the carto formula a big deal?

2023-04-11 15:26 UTC, Otterverse commented
> > So a couple of inline comments as well, but overall... this looks to provide "bin/carto_grpc_server" just like the previous formula does. As such, is there a reason this isn't just replacing the old one? If there is, then it needs a conflicts_with warning at least.
> 
> The slam team would like to be able to get this new formula out & working before needing to update docs. We are trying to prevent the need for lockstep deployments in coordination with Docs updates.
> 
> If we can assume nobody is going to use this new formula outside of viam until we update the docs, is the conflict with the carto formula a big deal?

It's pretty simple to add. It's just one line at the top of the formula, and it'll correctly warn people to uninstall the other formula first. See https://docs.brew.sh/Formula-Cookbook#specifying-conflicts-with-other-formulae

2023-04-11 16:24 UTC, kkufieta commented on Formula/cartographer-module.rb
> +    bin.install "viam-cartographer/build/carto_grpc_server"
Great question. A few thoughts:
1. What does "conflict with" really mean? In this case, if you installed one and then the other, wouldn't it just overwrite `carto_grpc_server` with the same binary?
2. We decided not to replace `carto-grpc-server.rb` with the module version because this would break the documentation. We figured we'd follow the following steps: 1) Add the module brew packages and AppImages, 2) Update the documentation to use the brew packages & AppImages, and 3) Delete the grpc server brew packages and AppImages. This leads me to assume we have these choices:
    1. We follow the steps as outlined and temporarily allow those brew packages to have a conflict without `conflicts_with`. Provided that we have not documented the cartographer and orbslam modules anywhere nor provided instructions on how to use them, it is unlikely that users would install those packages within this relatively short time.
    2. We follow the steps as outlined and add a `conflicts_with` to those two brew packages. (Question: How would this be handled for the AppImages?) Once the documentation is updated, we remove the grpc server brew packages & AppImages and remove `conflicts_with`.
    3. We add all four PRs (two PRs for AppImages and two PRs for the brew packages) into the pipeline without merging them yet - update the documentation - and then merge all PRs simultaneously. @nicksanford @EshaMaharishi  putting this on the table again.

2023-04-11 17:53 UTC, kkufieta commented on Formula/cartographer-module.rb
> +    lib.install "viam-cartographer/build/libviam-cartographer.a"
No! Removed.

2023-04-11 17:53 UTC, kkufieta commented on Formula/cartographer-module.rb
> +  depends_on "cairo"
Removed what was not necessary.

2023-04-11 17:54 UTC, kkufieta commented on Formula/cartographer-module.rb
> +    bin.install "viam-cartographer/build/carto_grpc_server"
Added a `conflicts_with`

2023-04-11 18:40 UTC, EshaMaharishi commented on Formula/cartographer-module.rb
> +    bin.install "viam-cartographer/build/carto_grpc_server"
I think it's okay to do 2i (if it's not a big deal to temporarily have a conflicting formula) or 2ii. (@Otterverse , not sure if it was clear that we were planning to remove `carto-grpc-server.rb` shortly)

2023-04-12 15:59 UTC, Otterverse approved these changes
LGTM

2023-04-12 16:47 UTC, nicksanford approved these changes
I was able to install this formula on an M1 mac:
```
➜  homebrew-brews git:(kk/rsdk-2022-add-carto-module) brew install --build-from-source ./Formula/cartographer-module.rb

 Error: Failed to load cask: ./Formula/cartographer-module.rb
Cask 'cartographer-module' is unreadable: wrong constant name #<Class:0x000000011de85940>
Warning: Treating ./Formula/cartographer-module.rb as a formula.
==> Fetching cartographer-module
==> Cloning https://github.com/viamrobotics/viam-cartographer.git
Cloning into '/Users/nicksanford/Library/Caches/Homebrew/cartographer-module--git'...
==> Checking out tag v0.3.1
HEAD is now at 5c3e8df RSDK-2393 Remove Name Parameter from SLAM Functions (#40)
Submodule 'viam-cartographer/cartographer' (https://github.com/cartographer-project/cartographer) registered for path 'viam-cartographer/cartographer'
Cloning into '/Users/nicksanford/Library/Caches/Homebrew/cartographer-module--git/viam-cartographer/cartographer'...
Submodule path 'viam-cartographer/cartographer': checked out 'ef00de2317dcf7895b09f18cc4d87f8b533a019b'
/Users/nicksanford/Library/Caches/Homebrew/cartographer-module--git/viam-cartographer/cartographer
==> make buf
==> make build
^G^G==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
🍺  /opt/homebrew/Cellar/cartographer-module/0.3.1: 15 files, 47.5MB, built in 1 minute 36 seconds
==> Running `brew cleanup cartographer-module`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
 ```

and I also confirmed I was able to run it successfully on an M1 mac host with the following config:
```
{
  "components": [
    {
      "model": "viam:lidar:rplidar",
      "attributes": {
      "device_path": "/dev/tty.usbserial-0001"
      },
      "name": "rplidar",
      "namespace": "rdk",
      "type": "camera",
      "depends_on": []
    }
  ],
  "services": [
    {
      "name": "slam-test",
      "model": "viam:slam:cartographer",
      "type": "slam",
      "attributes": {
        "port": "localhost:8083",
        "data_dir": "/Users/nicksanford/test-delete-me",
        "delete_processed_data": true,
        "use_live_data": true,
        "map_rate_sec": 30,
        "sensors": [
          "rplidar"
        ],
        "config_params": {
          "optimize_on_start": "true",
          "num_range_data": "100",
          "mode": "2d",
          "max_submaps_to_keep": "2"
        }
      }
    }
  ],
  "modules": [
    {
      "executable_path": "/opt/homebrew/bin/rplidar-module",
      "name": "rplidar_module"
    },
    {
      "executable_path": "/opt/homebrew/bin/cartographer-module",
      "name": "cartographer-module"
    }
  ]
}
```

2023-04-12 17:33 UTC, EshaMaharishi approved these changes

2023-04-12 17:33 UTC, EshaMaharishi commented on Formula/cartographer-module.rb
> +  def install
[note to self] This line clones the github repo pointed to by `url` above and `cd`'s into it (https://github.com/syhw/homebrew/blob/174cc1183a7d45e4c87efbc7715ea1016234715c/Library/Contributions/example-formula.rb#L247-L249).

2023-04-12 17:33 UTC, EshaMaharishi commented on Formula/cartographer-module.rb
> +    share.install "viam-cartographer/cartographer/configuration_files/trajectory_builder_3d.lua" => "cartographer/lua_files/"
[note to self] We are moving the lua files from their locations in the cloned repo's to the directory represented by the `share` variable.

Lua is a programming language with C-like syntax.

viam-cartographer and cartographer are using lua for some config files:

* slam_service.h stores the names of some lua files [here](https://github.com/viamrobotics/viam-cartographer/blob/4de47ffa3db4f3583f99546f53477c8a07528c84/viam-cartographer/src/slam_service/slam_service.h#L234-L237).
* config.cc determines the directory to look for the files in [here](https://github.com/viamrobotics/viam-cartographer/blob/4de47ffa3db4f3583f99546f53477c8a07528c84/viam-cartographer/src/slam_service/config.cc#L80-L91) based on the directory the executable is stored in. This is why we need to move the lua files to the `share` directory through these `share.install` lines`.
* slam_service.cc then uses the lua files during setup [here](https://github.com/viamrobotics/viam-cartographer/blob/4de47ffa3db4f3583f99546f53477c8a07528c84/viam-cartographer/src/slam_service/slam_service.cc#L305-L316).

2023-04-12 17:33 UTC, EshaMaharishi commented on Formula/cartographer-module.rb
> +  depends_on "pcl"
[open question] I'm not sure why these are runtime dependencies. However, I'm approving the PR as-is since our existing carto-grpc-server.rb includes these and other dependencies that we realized aren't actually needed. Would be nice to understand this better at some point.

2023-04-12 17:52 UTC, merged