RSDK-2024 - Add an orbslam3 module brew package
viamrobotics/homebrew-brews pull request #22
Opened 2023-04-10 19:48 UTC by kkufieta

Ticket: https://viam.atlassian.net/browse/RSDK-2024

**Done:** Add the orb-slam3-module brew package

**Note:** The added file is identical to orb-grpc-server.rb except for one line that I've highlighted.

**Tested on:** MacOS x86_64 (installed only since it does not function properly on macOS)

2023-04-10 19:49 UTC, kkufieta commented on Formula/orb-slam3-module.rb
> +    bin.install "bin/orb-slam3-module"
This is the only difference compared to orb-grpc-server.rb

2023-04-10 19:58 UTC, kkufieta commented on Formula/orb-slam3-module.rb
> +  desc "Viam ORB_SLAM3 modular service"
This is one of two differences compared to orb-grpc-server.rb (the other one being the added binary below).

2023-04-10 20:08 UTC, EshaMaharishi approved these changes
LGTM once https://github.com/viamrobotics/homebrew-brews/pull/21#discussion_r1162029159 is resolved

2023-04-10 20:45 UTC, Otterverse requested changes
Has the same conflict issue as carto... same questions here as well (e.g. why not just replace the old formula with this one?) Otherwise looks fine.

2023-04-10 20:45 UTC, Otterverse commented on Formula/orb-slam3-module.rb
> +    bin.install "viam-orb-slam3/bin/orb_grpc_server"
Same comments as carto... this conflicts with the existing formula.

2023-04-11 18:00 UTC, kkufieta commented on Formula/orb-slam3-module.rb
> +    bin.install "viam-orb-slam3/bin/orb_grpc_server"
Added a `conflicts_with`

2023-04-12 16:00 UTC, Otterverse approved these changes
LGTM

2023-04-12 16:18 UTC, nicksanford approved these changes
I confirmed I'm able to build it on an M1 mac:
```➜  homebrew-brews git:(kk/rsdk-2024-add-orbslam-module) brew install --build-from-source ./Formula/orb-slam3-module.rb

Error: Failed to load cask: ./Formula/orb-slam3-module.rb
Cask 'orb-slam3-module' is unreadable: wrong constant name #<Class:0x0000000133e1b390>
Warning: Treating ./Formula/orb-slam3-module.rb as a formula.
==> Fetching orb-slam3-module
==> Cloning https://github.com/viamrobotics/viam-orb-slam3.git
Updating /Users/nicksanford/Library/Caches/Homebrew/orb-slam3-module--git
==> Checking out tag v0.3.1
HEAD is now at 3726e0f RSDK-2393 Remove Name Parameter from SLAM Functions (#37)
HEAD is now at 3726e0f RSDK-2393 Remove Name Parameter from SLAM Functions (#37)
Entering 'viam-orb-slam3/ORB_SLAM3'
/Users/nicksanford/Library/Caches/Homebrew/orb-slam3-module--git/viam-orb-slam3/ORB_SLAM3
==> make buf
==> make build
^Gc==> install_name_tool -change /tmp/orb-slam3-module-20230412-3588-1p4fd7x/viam-orb-slam3/ORB_SLAM3/Thirdparty/DBoW2/lib/libDBoW2.dyli
==> install_name_tool -change /tmp/orb-slam3-module-20230412-3588-1p4fd7x/viam-orb-slam3/ORB_SLAM3/Thirdparty/g2o/lib/libg2o.dylib /o
==> install_name_tool -change /tmp/orb-slam3-module-20230412-3588-1p4fd7x/viam-orb-slam3/ORB_SLAM3/Thirdparty/DBoW2/lib/libDBoW2.dyli
==> install_name_tool -change /tmp/orb-slam3-module-20230412-3588-1p4fd7x/viam-orb-slam3/ORB_SLAM3/Thirdparty/g2o/lib/libg2o.dylib /o
==> install_name_tool -change /tmp/orb-slam3-module-20230412-3588-1p4fd7x/viam-orb-slam3/ORB_SLAM3/lib/libORB_SLAM3.dylib /opt/homebr
🍺  /opt/homebrew/Cellar/orb-slam3-module/0.3.1: 10 files, 187.4MB, built in 2 minutes 18 seconds
==> Running `brew cleanup orb-slam3-module`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

2023-04-12 17:49 UTC, merged