homebrew formula for intel camera server
viamrobotics/homebrew-brews pull request #3
Opened 2022-10-24 18:49 UTC by bhaney

Made a homebrew formula for the intel realsense GRPC server, compiles and seems to work on my M1 Mac, OS Version 12.4. (though it took a long while to get the realsense hardware itself to connect to the mac)

2022-10-24 18:49 UTC, bhaney commented
@tessavitabile FYI - no need to review this, but just letting you know about its existence

2022-10-24 18:50 UTC, bhaney commented on Formula/viam-rs-camera-server.rb
> +class ViamRsCameraServer < Formula
Not sure what to call this. Are there issues with trademarks if we call it "ViamRealSenseCameraServer"?

2022-10-24 18:55 UTC, bhaney commented on Formula/viam-rs-camera-server.rb
> +    bin.install "intelrealgrpcserver"
not sure about the name- though this is what we've always called it.

2022-10-24 23:16 UTC, Otterverse requested changes
A couple of minor tweaks suggested. One thing that stymied me in testing this was that brew's opencv build for linux is kinda broken. I had to install opencv from source `brew reinstall -s opencv` in order to make it work, otherwise it gave me library problems.

2022-10-24 23:16 UTC, Otterverse commented on Formula/viam-rs-camera-server.rb
> +  depends_on "openssl"
Is this explicitly needed? It builds without it, and causes some (non-fatal) conflicts with grpc when explicitly required here.

2022-10-25 16:53 UTC, bhaney commented on Formula/viam-rs-camera-server.rb
> +  depends_on "openssl"
not explicitly needed, I'll remove this line

2022-10-25 18:17 UTC, bhaney commented on Formula/viam-rs-camera-server.rb
> +    system "mkdir", "grpc/bin"
will remove

2022-10-25 18:18 UTC, bhaney commented on Formula/viam-rs-camera-server.rb
> +class ViamRsCameraServer < Formula
since the binary is called intelrealgrpcserver, I'll just call it that

2022-10-25 18:25 UTC, Otterverse approved these changes
Was just about to point out that the filename and classname have to match in a weird way, but you caught/fixed it. LGTM!

2022-10-25 18:26 UTC, merged

2022-10-25 18:26 UTC, Otterverse commented
> made the changes, but should I just mention the `brew reinstall -s opencv` issues in the README for camera-servers?

I think that's ONLY a linux issue on certain linuxes, and generally people shouldn't be using this on linux (we have an appimage that "just works" without needing a whole ecosystem there.)