[DATA-693] initial cartographer formula
viamrobotics/homebrew-brews pull request #8
Opened 2022-12-08 08:12 UTC by JohnN193

brew formula for installing cartographer. Currently tested on M1 mac and x86 mac.

https://viam.atlassian.net/browse/DATA-693

2022-12-08 20:02 UTC, JohnN193 commented on Formula/carto-grpc-server.rb
> +    tag: "v0.1.10"
will not merge until next release occurs in order to include some necessary commits from the slam repo

2022-12-09 00:16 UTC, Otterverse requested changes
So it looks mostly good (save a nit below about formatting) But... cartographer itself fails to compile under linux, both against 0.1.10 and with --HEAD.

The error I hit is this:

```
/tmp/carto-grpc-server-20221208-1460499-kyx5mh/slam-libraries/viam-cartographer/src/io/file_handler.cc: In function 'double viam::io::ReadTimeFromTimestamp(std::string)':
/tmp/carto-grpc-server-20221208-1460499-kyx5mh/slam-libraries/viam-cartographer/src/io/file_handler.cc:104:16: error: 'get_time' is not a member of 'std'; did you mean 'gmtime'?
  104 |     ss >> std::get_time(&dt, time_format.c_str());
      |                ^~~~~~~~
      |                gmtime
```
I'm pretty sure that's just because the file in question needs `#include <iomanip>` (which is where get_time now resides on many compilers)

That needs to be resolved before this goes into a public brew tap.

2022-12-09 14:35 UTC, tessavitabile requested changes
Looks good!

2022-12-09 14:35 UTC, tessavitabile commented on Formula/carto-grpc-server.rb
> +    tag: "v0.1.10"
I found for orbslam that it was necessary to specify the revision along with the tag in order for submodules to be downloaded when installing without `--HEAD`.

2022-12-12 16:33 UTC, tessavitabile commented on Formula/carto-grpc-server.rb
> +    tag: "v0.1.10"
Huh, what I found for orbslam was that when installing without `--HEAD`, it downloads the artifacts associated with the tag, which don't include submodules.

2022-12-14 23:26 UTC, JohnN193 commented
Kk updated the slam repo to include the missing include, just need an updated version tag for slam

2022-12-15 00:35 UTC, Otterverse approved these changes
LGTM, provided you wait for an updated tag that builds without "--HEAD"

2022-12-15 14:14 UTC, tessavitabile approved these changes
LGTM. It's fine to do a patch release for SLAM yourself. Let me know if you need any information on how to do that.

2022-12-15 16:06 UTC, merged